# The Docker image that will be used to build your app
image: node:lts

deploy-cloudcatalog:
  pages: true
  script:
    - cd cloudcatalog
    - npm install
    # Specify the steps involved to build your app here
    - npm run build
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public
